:PROPERTIES:
:ID:       0F78767D-42FF-4027-B3A2-26CA1898F788
:END:
#+title: obi

obi is what I'm tentatively calling an effort to expand use of [[id:04B03591-50E7-41E2-A2A5-0C2893FAD39C][org-babel]].
The actual name is just slamming together the ~ob~ used for org-babel
and Star Wars, but it could also theoretically acquire a backronym
like Org Babel Improved.

** Background

I've recently taken to using org babel very heavily...and that mostly
comes down to treating those files as a primary interface/shell. This
therefore seems likely to expand beyond what org-babel may typically
come with org-babel: while all the building blocks seem to be there,
there may be some specific extensions and conventions that
fall out of using it more extensively.

One of the other fairly significant goals is that while I'll be using
obi with org-babel and emacs for the foreseeable future, I'd also want
that to be detachable. Therefore everything should remain fully
transparent so that what is done could be readily extracted to some
other interface like a boring old shell.

Beyond babel and evident alternatives like Jupyter, I'm also likely to
want to draw on ideas from other systems that had interfaces similar
to interactive notebooks such as the Acme editor and Oberon.

* TODO obi/execute-src-block
:PROPERTIES:
:ID:       31893E0D-17BB-4DE7-8C4D-9D98E2D23856
:END:

Splitting up [[id:D7816316-280D-4B7B-9420-3E33264E24D2][org-babel-execute-src-block]]

I'll start by just expecting to break up what is there.

** executor-type

Split out executor selection as it's a bit wordy for a let block.

Return any explicitly provided value, otherwise detect based on the
next character if it exists.

It seems like this may just be doing too much...maybe I want to split
out functions?
Within this function it looks like this is only used to produce a message?

Rather than decomposing this function maybe the first pass will be to
attempt to gut it...

** Cut to execute

Inferring from past experience that the specialized logic lives in the
~org:babel-execute:<lang>~ bodies leads me to zero in on that
logic. That needs "lang" which is extracted from "info". The first few
lets are therefore used.

** should evaluate

One variable that seems worth trying to get a handle on is whether
things will be evaluated. This is typically going to amount to whether
some functionality gets applied and would therefore seem most clearly
modeled as something equivalent to multiple phases where evaluation is
an optional phase, but it is currently handled as flags.
