:PROPERTIES:
:ID:       ED17C5B4-4002-4CC0-9FD0-4A72FD845229
:header-args: :results output :session o365 :async :var host_py="python3" :var venv="/tmp/o365" :var venv_py="/tmp/o365/bin/python" :python "/tmp/o365/bin/python"
:END:
#+title: office365

Office 365 is Microsoft's office suite...

While I've warmed up to Microsoft over the years I still remain pretty
unlikely to adopt Office 365 of my own free will...but them's the
breaks. I've setup a personal free account to work with this notebook.

* O365

Following search threads initially led me to the
https://github.com/O365/python-o365 library.

After kicking the tires a bit, I ended up moving off of it.  The
authentication wasn't quickly working (likely due to the many knobs
available on both ends), and when I started to dig through the code I
was left with concerns...some of which I also somewhat expected based
on the vibe of the code documentation (that seems unfair of me, but
the vibe was confirmed).

Overall the project doesn't align with my tastes...for something like
this I'd be particularly looking for some lightweight modeling on top
of fairly exposed API details, but the project instead felt like a
typical mass of relatively bloated and tangled OOP code - fairly poor
separation of concerns and even though it is focused on a single
platform (Office 365) it has the heft and indirection of something
striving to offer some kind of generalized functionality. If the code
had just worked I wouldn't have been bothered, but since it didn't
the details are not only contrary to my taste, but also got in the way
of jumping in to making things work.

* MSGraph SDK

I subsequently chased down the SDK offered by Microsoft:
https://github.com/microsoftgraph/msgraph-sdk-python.

This is potentially slightly more hidden given that it is oriented
towards the Graph API rather than the services that run on top of
that. The code is seemingly designed similarly where most of the code
seems to be generated off of the API definition.

This is at least more closely aligned with the rest of the ecosystem
and so far the code seems what would be expected from that type of
generation configuration. While I'm sticking with python to start
(since I'll be using python for other things and its a good scripting
option), this should also allow for easier jumping to other runtimes
if warranted.

* Outlook?

This page does mention mail as another API.
https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc
** Installation

#+begin_src shell :session venv-setup :results output
  ${host_py} -m venv ${venv}
  ${venv_py} -m pip install msgraph-sdk
#+end_src

#+RESULTS:
#+begin_example
host_py='python3'
venv='/tmp/o365'
venv_py='/tmp/o365/bin/python'
${host_py} -m venv ${venv}
${venv_py} -m pip install msgraph-sdk
Requirement already satisfied: msgraph-sdk in /private/tmp/o365/lib/python3.14/site-packages (1.58.0)
Requirement already satisfied: azure-identity>=1.12.0 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.25.3)
Requirement already satisfied: microsoft-kiota-serialization-json<2.0.0,>=1.8.0 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.10.3)
Requirement already satisfied: microsoft-kiota-serialization-text<2.0.0,>=1.8.0 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.10.3)
Requirement already satisfied: microsoft-kiota-serialization-form<2.0.0,>=1.8.0 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.10.3)
Requirement already satisfied: microsoft-kiota-serialization-multipart<2.0.0,>=1.8.0 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.10.3)
Requirement already satisfied: msgraph_core>=1.3.1 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph-sdk) (1.4.0)
Requirement already satisfied: microsoft-kiota-abstractions<1.11.0,>=1.10.3 in /private/tmp/o365/lib/python3.14/site-packages (from microsoft-kiota-serialization-form<2.0.0,>=1.8.0->msgraph-sdk) (1.10.3)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /private/tmp/o365/lib/python3.14/site-packages (from microsoft-kiota-abstractions<1.11.0,>=1.10.3->microsoft-kiota-serialization-form<2.0.0,>=1.8.0->msgraph-sdk) (1.42.1)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /private/tmp/o365/lib/python3.14/site-packages (from microsoft-kiota-abstractions<1.11.0,>=1.10.3->microsoft-kiota-serialization-form<2.0.0,>=1.8.0->msgraph-sdk) (1.42.1)
Requirement already satisfied: std-uritemplate>=2.0.0 in /private/tmp/o365/lib/python3.14/site-packages (from microsoft-kiota-abstractions<1.11.0,>=1.10.3->microsoft-kiota-serialization-form<2.0.0,>=1.8.0->msgraph-sdk) (2.0.10)
Requirement already satisfied: azure-core>=1.31.0 in /private/tmp/o365/lib/python3.14/site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.41.0)
Requirement already satisfied: cryptography>=2.5 in /private/tmp/o365/lib/python3.14/site-packages (from azure-identity>=1.12.0->msgraph-sdk) (49.0.0)
Requirement already satisfied: msal>=1.35.1 in /private/tmp/o365/lib/python3.14/site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.37.0)
Requirement already satisfied: msal-extensions>=1.2.0 in /private/tmp/o365/lib/python3.14/site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.3.1)
Requirement already satisfied: typing-extensions>=4.0.0 in /private/tmp/o365/lib/python3.14/site-packages (from azure-identity>=1.12.0->msgraph-sdk) (4.15.0)
Requirement already satisfied: requests>=2.21.0 in /private/tmp/o365/lib/python3.14/site-packages (from azure-core>=1.31.0->azure-identity>=1.12.0->msgraph-sdk) (2.34.2)
Requirement already satisfied: cffi>=2.0.0 in /private/tmp/o365/lib/python3.14/site-packages (from cryptography>=2.5->azure-identity>=1.12.0->msgraph-sdk) (2.0.0)
Requirement already satisfied: pycparser in /private/tmp/o365/lib/python3.14/site-packages (from cffi>=2.0.0->cryptography>=2.5->azure-identity>=1.12.0->msgraph-sdk) (3.0)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /private/tmp/o365/lib/python3.14/site-packages (from PyJWT[crypto]<3,>=1.0.0->msal>=1.35.1->azure-identity>=1.12.0->msgraph-sdk) (2.13.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /private/tmp/o365/lib/python3.14/site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->msgraph-sdk) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /private/tmp/o365/lib/python3.14/site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->msgraph-sdk) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /private/tmp/o365/lib/python3.14/site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->msgraph-sdk) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /private/tmp/o365/lib/python3.14/site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->msgraph-sdk) (2026.5.20)
Requirement already satisfied: microsoft-kiota-authentication-azure<2.0.0,>=1.10.1 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph_core>=1.3.1->msgraph-sdk) (1.10.3)
Requirement already satisfied: microsoft-kiota-http<2.0.0,>=1.10.1 in /private/tmp/o365/lib/python3.14/site-packages (from msgraph_core>=1.3.1->msgraph-sdk) (1.10.3)
Requirement already satisfied: httpx>=0.23.0 in /private/tmp/o365/lib/python3.14/site-packages (from httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (0.28.1)
Requirement already satisfied: aiohttp>=3.8.0 in /private/tmp/o365/lib/python3.14/site-packages (from microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (3.14.1)
Requirement already satisfied: anyio in /private/tmp/o365/lib/python3.14/site-packages (from httpx>=0.23.0->httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (4.13.0)
Requirement already satisfied: httpcore==1.* in /private/tmp/o365/lib/python3.14/site-packages (from httpx>=0.23.0->httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (1.0.9)
Requirement already satisfied: h11>=0.16 in /private/tmp/o365/lib/python3.14/site-packages (from httpcore==1.*->httpx>=0.23.0->httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /private/tmp/o365/lib/python3.14/site-packages (from httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /private/tmp/o365/lib/python3.14/site-packages (from h2<5,>=3->httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /private/tmp/o365/lib/python3.14/site-packages (from h2<5,>=3->httpx[http2]>=0.23.0->msgraph_core>=1.3.1->msgraph-sdk) (4.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /private/tmp/o365/lib/python3.14/site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure<2.0.0,>=1.10.1->msgraph_core>=1.3.1->msgraph-sdk) (1.24.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /private/tmp/o365/lib/python3.14/site-packages (from opentelemetry-sdk>=1.27.0->microsoft-kiota-abstractions<1.11.0,>=1.10.3->microsoft-kiota-serialization-form<2.0.0,>=1.8.0->msgraph-sdk) (0.63b1)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /private/tmp/o365/bin/python -m pip install --upgrade pip
[?2004hecho 'ob_comint_async_shell_end_1c0a77fc-fdb5-46c3-876c-1965e7585e0a'[?2004l
#+end_example

#+begin_src python
  help('modules msgraph')
#+end_src

#+RESULTS:
#+begin_example
Here is a list of modules whose name or summary contains 'msgraph'.
If there are any, enter a module name to get more help.

msgraph - Python client for the Microsoft Graph API
msgraph._version 
msgraph.graph_request_adapter 
msgraph.graph_service_client 
msgraph_core - Core component of the Microsoft Graph Python SDK consisting of HTTP/Graph Client and a configurable middleware pipeline (Preview).
msgraph_core._constants - Application constants. All defaults can be changed when initializing a client
msgraph_core._enums 
msgraph_core.authentication 
msgraph_core.authentication.azure_identity_authentication_provider 
msgraph_core.base_graph_request_adapter 
msgraph_core.graph_client_factory 
msgraph_core.middleware 
msgraph_core.middleware.async_graph_transport 
msgraph_core.middleware.options 
msgraph_core.middleware.options.graph_telemetry_handler_option 
msgraph_core.middleware.request_context 
msgraph_core.middleware.telemetry 
msgraph_core.models 
msgraph_core.models.large_file_upload_session 
msgraph_core.models.page_result - This module defines the PageResult class which represents a page of
msgraph_core.models.upload_result 
msgraph_core.requests 
msgraph_core.requests.batch_request_builder 
msgraph_core.requests.batch_request_content 
msgraph_core.requests.batch_request_content_collection 
msgraph_core.requests.batch_request_item 
msgraph_core.requests.batch_response_content 
msgraph_core.requests.batch_response_content_collection 
msgraph_core.requests.batch_response_item 
msgraph_core.tasks 
msgraph_core.tasks.large_file_upload 
msgraph_core.tasks.page_iterator - This module contains the PageIterator class which is used to
#+end_example
I'm expecting to use o365.

https://github.com/O365/python-o365
https://o365.github.io/python-o365/latest/index.html

I signed up for outlook...but I don't want to pay for Office 365.

I'm also having a bunch of errors on the site itself which does not inspire confidence.

Creating an azure account...

Configuring an azure account unlocks the Entra ID management screen.

* [[id:A3C4A953-79CA-4160-AB26-A6EDCCD8AC09][Setup the Environment]]

#+begin_src shell :session venv-setup :results output
  ${host_py} -m venv ${venv}
  ${venv_py} -m pip install o365
#+end_src

#+RESULTS:
#+begin_example
host_py='python3'
venv='/tmp/o365'
venv_py='/tmp/o365/bin/python'
${host_py} -m venv ${venv}
${venv_py} -m pip install o365
Collecting o365
  Downloading o365-2.1.9-py3-none-any.whl.metadata (3.6 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting beautifulsoup4>=4.12.3 (from o365)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting msal>=1.31.1 (from o365)
  Downloading msal-1.37.0-py3-none-any.whl.metadata (11 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting python-dateutil>=2.9.0.post0 (from o365)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting requests>=2.32.3 (from o365)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tzdata>=2024.2 (from o365)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting tzlocal>=5.2 (from o365)
  Downloading tzlocal-5.4-py3-none-any.whl.metadata (7.7 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.12.3->o365)
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4>=4.12.3->o365)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting PyJWT<3,>=1.0.0 (from PyJWT[crypto]<3,>=1.0.0->msal>=1.31.1->o365)
  Using cached pyjwt-2.13.0-py3-none-any.whl.metadata (3.4 kB)
Collecting cryptography<51,>=2.5 (from msal>=1.31.1->o365)
  Using cached cryptography-49.0.0-cp311-abi3-macosx_11_0_arm64.whl.metadata (4.3 kB)
Collecting cffi>=2.0.0 (from cryptography<51,>=2.5->msal>=1.31.1->o365)
  Using cached cffi-2.0.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.6 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.3->o365)
  Using cached charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests>=2.32.3->o365)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.3->o365)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests>=2.32.3->o365)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography<51,>=2.5->msal>=1.31.1->o365)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting six>=1.5 (from python-dateutil>=2.9.0.post0->o365)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading o365-2.1.9-py3-none-any.whl (160 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading msal-1.37.0-py3-none-any.whl (123 kB)
Using cached cryptography-49.0.0-cp311-abi3-macosx_11_0_arm64.whl (4.0 MB)
Using cached pyjwt-2.13.0-py3-none-any.whl (31 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp314-cp314-macosx_10_15_universal2.whl (309 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached cffi-2.0.0-cp314-cp314-macosx_11_0_arm64.whl (181 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Downloading tzlocal-5.4-py3-none-any.whl (28 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: urllib3, tzlocal, tzdata, typing-extensions, soupsieve, six, PyJWT, pycparser, idna, charset_normalizer, certifi, requests, python-dateutil, cffi, beautifulsoup4, cryptography, msal, o365


Successfully installed PyJWT-2.13.0 beautifulsoup4-4.15.0 certifi-2026.5.20 cffi-2.0.0 charset_normalizer-3.4.7 cryptography-49.0.0 idna-3.18 msal-1.37.0 o365-2.1.9 pycparser-3.0 python-dateutil-2.9.0.post0 requests-2.34.2 six-1.17.0 soupsieve-2.8.4 typing-extensions-4.15.0 tzdata-2026.2 tzlocal-5.4 urllib3-2.7.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /private/tmp/o365/bin/python -m pip install --upgrade pip
[?2004hecho 'ob_comint_async_shell_end_0bd9768d-f7e2-4018-b9f9-b4e23418ebdc'[?2004l
#+end_example

** Modules

#+begin_src shell
  ${venv_py} -c "help('modules o365')"
#+end_src

#+RESULTS:
#+begin_example
host_py='python3'
venv='/tmp/o365'
venv_py='/tmp/o365/bin/python'
${venv_py} -c "help('modules o365')"

Here is a list of modules whose name or summary contains 'o365'.
If there are any, enter a module name to get more help.

O365 - A simple python library to interact with Microsoft Graph and other MS api
O365.account 
O365.address_book 
O365.calendar 
O365.category 
O365.connection 
O365.directory 
O365.drive 
O365.excel - 2019-04-15
O365.groups 
O365.mailbox 
O365.message 
O365.planner 
O365.sharepoint 
O365.subscriptions 
O365.tasks - Methods for accessing MS Tasks/Todos via the MS Graph api.
O365.teams 
O365.utils 
O365.utils.attachment 
O365.utils.casing 
O365.utils.consent 
O365.utils.decorators 
O365.utils.query 
O365.utils.range 
O365.utils.token 
O365.utils.utils 
O365.utils.windows_tz - Mapping from iana timezones to windows timezones and vice versa
[?2004hecho 'ob_comint_async_shell_end_97a1a6b9-e078-4f97-be1e-a5ad4f66d9be'[?2004l
#+end_example

* Setup Credentials

- Login to Entra https://entra.microsoft.com/#home
- This requires a directory managed account (which can be done by setting up Azure)
- Add Mail.Read to start

** Load Credentials

I'll store the credentials in a local ~my.secrets.ini~ file.

*** Load Credentials Values

#+begin_src python :tangle /tmp/o365/auth.py
  import configparser
  config = configparser.ConfigParser()
  config.read('my.secrets.ini')

  from O365 import Account
  auth_config = config['auth']
  tenant_id=auth_config['tenant_id']
  client_id=auth_config['client_id']
  client_secret=auth_config['client_secret_value']
  credentials = (client_id, client_secret)
#+end_src
