:PROPERTIES:
:ID:       04B03591-50E7-41E2-A2A5-0C2893FAD39C
:END:
#+title: org-babel

Org Babel is a literate programming environment using org mode in [[id:436EB0B7-811E-4828-BBF7-4126517DD7C6][emacs]].

As evidenced by this repository, I'm fairly keen on it.

I first started using it several years ago, but largely shelved it in favor of
lighter touch solutions, but more recently with the rise of using AI for coding
the model provided by org-babel seems particularly appropriate - resulting in options
like the babel files capturing what amount to live lab notebooks that were used to
drive the work of the agents.

* Languages

- [[id:222093AC-E4FC-4E90-B124-ADFFC31F6314][emacs-lisp]]
- [[id:002B2928-C32F-49F3-B93F-CBEEE215A7D7][python]]

* Arguments

** ~:results~

*** what is captured

**** value

The default, with some DWIM formatting.

#+begin_src emacs-lisp :results value
  (list 1 2 3)
#+end_src

#+RESULTS:
| 1 | 2 | 3 |

Some languages may require more help to actually return the value
(either due to inherent behavior or being run within some type of wrapper.

#+begin_src python :results value
  return (1,2,3)
#+end_src

#+RESULTS:
| 1 | 2 | 3 |

** ~:var~

Set the named variable to the provided value.
This seems to be supported by synthesizing relevant assignment statements.

*** String Literal

#+begin_src emacs-lisp :var foo="bar"
  (format "foo=%s" foo)
#+end_src

#+RESULTS:
: foo=bar

*** Numeric Literal

#+begin_src emacs-lisp :var foo=1
  (+ foo 2)
#+end_src

#+RESULTS:
: 3

*** Expression

#+begin_src emacs-lisp :var foo=(buffer-name)
  foo
#+end_src

#+RESULTS:
: 20260615111334-org_babel.org

*** Named Block

This can also make use of richer content like tables and lists.

#+name: foo
A line of text

#+begin_src emacs-lisp :var foo=foo
  foo
#+end_src

#+RESULTS:
: A line of text

*** Evaluated Block

Also just throw in a demonstration of passing the values across languages.

#+name: foo-block
#+begin_src emacs-lisp
  (concat "biz" "baz")
#+end_src

For this case parentheses can optionally be included after the block name.

#+begin_src python :var foo=foo-block
  return foo
#+end_src

#+RESULTS:
: bizbaz

* Configuration

** org-confirm-babel-evaluate

#+begin_src emacs-lisp
  (describe-variable 'org-confirm-babel-evaluate)
#+end_src

#+RESULTS:
#+begin_example
org-confirm-babel-evaluate is a variable defined in ‘ob-core.el’.

Its value is nil
Original value was t

Confirm before evaluation.
Require confirmation before interactively evaluating code
blocks in Org buffers.  The default value of this variable is t,
meaning confirmation is required for any code block evaluation.
This variable can be set to nil to inhibit any future
confirmation requests.  This variable can also be set to a
function which takes two arguments the language of the code block
and the body of the code block.  Such a function should then
return a non-nil value if the user should be prompted for
execution or nil if no prompt is required.

Warning: Disabling confirmation may result in accidental
evaluation of potentially harmful code.  It may be advisable
remove code block execution from ‘C-c C-c’ as further protection
against accidental code block evaluation.  The
‘org-babel-no-eval-on-ctrl-c-ctrl-c’ variable can be used to
remove code block execution from the ‘C-c C-c’ keybinding.

  This variable is safe as a file local variable if its value
  satisfies the predicate which is a compiled expression.
  This variable was introduced, or its default value was changed, in
  version 24.1 of Emacs.
  You can customize this variable.

#+end_example

YOLO

#+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+end_src

** org-src-tab-acts-natively

#+begin_src emacs-lisp
  (describe-variable 'org-src-tab-acts-natively)
#+end_src

#+RESULTS:
#+begin_example
org-src-tab-acts-natively is a variable defined in ‘org-src.el’.

Its value is t

If non-nil, TAB uses the language’s major-mode binding in code blocks.

  This variable was introduced, or its default value was changed, in
  version 9.4 of the Org package that is part of Emacs 27.2.
  You can customize this variable.

#+end_example

#+begin_src emacs-lisp
  (setq org-src-tab-active-natively t)
#+end_src

* Practices

** Packaging Up Behaviors
:PROPERTIES:
:ID:       DF79A72C-570A-49C8-A566-D494C59F732C
:END:

A major driver fro using org-babel is that it keeps the machinery
exposed and allows working with some sizeable chunks. As part of this
there will be a balance between approaches like copypasta and more
in-built functionality.

The rule of thumb is likely to keep things either very dumb and simple
(and rely on copypasta) or have them clearly defined as built in to
the engine. The undesriable middle ground is where functionality is
both not clearly defined as something that is provided, nor is it
clearly visible.
