:PROPERTIES:
:ID:       12BC5AB3-D75B-43BC-A51E-C8CD80AAE829
:header-args: :session tla :var venv="/tmp/tla" :python /tmp/tla/bin/python :async :results output
:END:
#+title: tla+

TLA+ is a modeling language to aid with formal verification.

https://github.com/tlaplus/tlaplus

These are typically run within the toolbox,
docs are available here for more manual invocation:
https://lamport.azurewebsites.net/tla/standalone-tools.html?back-link=tools.html

* Interface Selection

The standard documentation around CLI use is fairly minimal on top of
invoking [[id:72258C97-F88E-4498-825D-A7447EC008AA][java]] which is likely to get cumbersome. Beyond that
the core tools are stitched together with some files in fairly simpler
formats, but the toolbox is typically expected to manage those files.

There seem to be two provided wrappers to support CLI use.

** https://github.com/pmer/tla-bin
This is a very thin wrapper which uses the [[id:3368C2A8-C34F-45C2-8601-1735BD712D74][shell]] to absorb the Java
invocation, but this doesn't seem to address the other configuration needs.

** https://github.com/hwayne/tlacli
Is a [[id:002B2928-C32F-49F3-B93F-CBEEE215A7D7][python]] wrapper created by an author of one of the TLA+ books.
It has the advantages that it does handle some of the configuration
needs, and that it's python presumably makes it easier to wire up as a
[[id:9D4EC4DC-FC1D-430D-B834-CB0916949915][langchain]] tool.

This library is older and currently also pulls in pkg_resources which
been removed in newer versions of python setuptools. Given that the
library is fairly small and comes with a prominent disclaimer
regarding limited use, I'll tentantively plan on extracting the core
pieces here.

* Installation

Installation of TLA+ itself is currently absent but is provided by the
tla-bin installation instructions. I'll have to retrofit this when it
is encountered.

#+begin_src shell :session setup-venv
  python -m venv ${venv}
  ${venv}/bin/python -m pip install tlacli "setuptools<82"
#+end_src

#+RESULTS:
#+begin_example
venv='/tmp/tla'
python -m venv ${venv}
${venv}/bin/python -m pip install tlacli "setuptools<82"
Requirement already satisfied: tlacli in /private/tmp/tla/lib/python3.14/site-packages (0.0.1)
Collecting setuptools<82
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Using cached setuptools-81.0.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
Successfully installed setuptools-81.0.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /private/tmp/tla/bin/python -m pip install --upgrade pip
[?2004hecho 'ob_comint_async_shell_end_64989235-1e2c-414b-a8c8-00ff29ea50f2'[?2004l
#+end_example

#+begin_src shell
  . ${venv}/bin/activate
  tlacli --help
#+end_src

#+RESULTS:
#+begin_example
(tla) org_babel_sh_prompt> venv='/tmp/tla'
(tla) org_babel_sh_prompt> . ${venv}/bin/activate
(tla) org_babel_sh_prompt> tlacli --help
/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
usage: tlacli [-h] {check,tlc,translate,pc,pluscal} ...

positional arguments:
  {check,tlc,translate,pc,pluscal}
                        Which TLA+ tool to run
    check (tlc)         Run the TLC model checker on a TLA+ spec.
    translate (pc, pluscal)
                        Translate pluscal into TLA+

options:
  -h, --help            show this help message and exit
(tla) org_babel_sh_prompt> [?2004hecho 'ob_comint_async_shell_end_ca41b204-160a-45ec-9ae4-4e7bd2bc5473'[?2004l
#+end_example

* Sample

#+name: wire
#+begin_example
---------- MODULE wire --------
EXTENDS Integers
(*--algorithm wire
variables
  people = {"alice", "bob"},
  acc = [p \in people |-> 5],

define
  NoOverdrafts == \A p \in people: acc[p] >= 0
  EventuallyConsistent == <>[](acc["alice"] + acc["bob"] = 10)
end define;

process Wire \in 1..2
  variables
    sender = "alice",
    receiver = "bob",
    amount \in 1..acc[sender];

  begin
    CheckAndWithdraw:
      if amount <= acc[sender] then
        acc[sender] := acc[sender] - amount;
        Deposit:
          acc[receiver] := acc[receiver] + amount;
      end if;
end process;
end algorithm;*)
===============================
#+end_example

These tools seem to have a fair amount of file conventions that
inhibits use of things like stdin.

* translate

#+begin_src shell
  . ${venv}/bin/activate
  tlacli translate --help
#+end_src

#+RESULTS:
#+begin_example
(tla) org_babel_sh_prompt> venv='/tmp/tla'
(tla) org_babel_sh_prompt> . ${venv}/bin/activate
(tla) org_babel_sh_prompt> tlacli translate --help
/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
usage: tlacli translate [-h] Specfile

positional arguments:
  Specfile    The specfile.tla

options:
  -h, --help  show this help message and exit
(tla) org_babel_sh_prompt> [?2004hecho 'ob_comint_async_shell_end_250302b9-54c0-409a-9490-2b996fa09e89'[?2004l
#+end_example

** Example

#+begin_src shell :stdin wire :dir venv
  cat > wire.tla
  . ${venv}/bin/activate
  tlacli translate wire.tla
  cat wire.tla
#+end_src

#+RESULTS:
#+begin_example
/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

pcal.trans Version 1.9 of 10 July 2019
Parsing completed.
Translation completed.
New file wire.tla written.

---------- MODULE wire --------
EXTENDS Integers
(*--algorithm wire
variables
  people = {"alice", "bob"},
  acc = [p \in people |-> 5],
  sender = "alice",
  receiver = "bob",
  amount \in 1..6;

define
  NoOverdrafts == \A p \in people: acc[p] >= 0
end define;

begin
  Withdraw:
    acc[sender] := acc[sender] - amount;
  Deposit:
    acc[receiver] := acc[receiver] + amount;
end algorithm;*)
\* BEGIN TRANSLATION - the hash of the PCal code: PCal-b1c4bd6a54b09b98329a7acd38ea483e
VARIABLES people, acc, sender, receiver, amount, pc

(* define statement *)
NoOverdrafts == \A p \in people: acc[p] >= 0


vars == << people, acc, sender, receiver, amount, pc >>

Init == (* Global variables *)
        /\ people = {"alice", "bob"}
        /\ acc = [p \in people |-> 5]
        /\ sender = "alice"
        /\ receiver = "bob"
        /\ amount \in 1..6
        /\ pc = "Withdraw"

Withdraw == /\ pc = "Withdraw"
            /\ acc' = [acc EXCEPT ![sender] = acc[sender] - amount]
            /\ pc' = "Deposit"
            /\ UNCHANGED << people, sender, receiver, amount >>

Deposit == /\ pc = "Deposit"
           /\ acc' = [acc EXCEPT ![receiver] = acc[receiver] + amount]
           /\ pc' = "Done"
           /\ UNCHANGED << people, sender, receiver, amount >>

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == pc = "Done" /\ UNCHANGED vars

Next == Withdraw \/ Deposit
           \/ Terminating

Spec == Init /\ [][Next]_vars

Termination == <>(pc = "Done")

\* END TRANSLATION - the hash of the generated TLA code (remove to silence divergence warnings): TLA-f49700449c9bc05bd73fd91572d0e484
===============================
#+end_example

* check

** Help

#+begin_src shell
  . ${venv}/bin/activate
  tlacli check --help
#+end_src

#+RESULTS:
#+begin_example
(tla) org_babel_sh_prompt> venv='/tmp/tla'
(tla) org_babel_sh_prompt> . ${venv}/bin/activate
(tla) org_babel_sh_prompt> tlacli check --help
/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
usage: tlacli check [-h] [--spec SPEC] [--cfg CFG] [--invariant [INVARIANT ...]] [--property [PROPERTY ...]]
                    [--constant CONSTANT CONSTANT] [--model-values MODEL_VALUES [MODEL_VALUES ...]]
                    [--cfg-out CFG_OUT] [--tlc-workers TLC_WORKERS]
                    Specfile

positional arguments:
  Specfile              The specfile.tla

options:
  -h, --help            show this help message and exit
  --cfg-out CFG_OUT     Where to save the cfg file, if you want to reuse it

cfg_args:
  Configuration values for the TLA+ spec

  --spec, --specification SPEC
                        The TLA+ specification operator, defaults to Spec
  --cfg CFG             A template cfg for default values
  --invariant [INVARIANT ...]
                        Adds argument as model invariant, may be specified multiple times
  --property [PROPERTY ...]
                        Adds argument as model temporal property, may be specified multiple times
  --constant CONSTANT CONSTANT
                        {name} {value}
  --model-values MODEL_VALUES [MODEL_VALUES ...]
                        list of model values

tlc_args:
  Runtime values for the TLC model checker

  --tlc-workers TLC_WORKERS
                        The number of worker threads to use (default is number of cpus)
(tla) org_babel_sh_prompt> [?2004hecho 'ob_comint_async_shell_end_4fa60f4f-dab9-453a-b319-a699235bcfc8'[?2004l
#+end_example

** Example

#+begin_src shell :stdin wire :dir venv
  cat > wire.tla
  . ${venv}/bin/activate
  tlacli translate wire
  tlacli check --invariant NoOverdrafts -- wire.tla
#+end_src

#+RESULTS:
#+begin_example
/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

pcal.trans Version 1.9 of 10 July 2019
Parsing completed.
Translation completed.
New file wire.tla written.

/private/tmp/tla/lib/python3.14/site-packages/tlacli/tools/tlc.py:9: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

TLC2 Version 2.15 of Day Month 20?? (rev: d5b5a7f)
Warning: Please run the Java VM which executes TLC with a throughput optimized garbage collector by passing the "-XX:+UseParallelGC" property.
(Use the -nowarning option to disable this warning.)
Running breadth-first search Model-Checking with fp 52 and seed 7145458449092254086 with 10 workers on 10 cores with 8192MB heap and 64MB offheap memory [pid: 21550] (Mac OS X 26.3.1 aarch64, Homebrew 21.0.11 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /Users/mwhipple/memex/wire.tla
Parsing file /private/var/folders/y1/qpq5h9vd44dgw77dx8jb00380000gn/T/Integers.tla
Parsing file /private/var/folders/y1/qpq5h9vd44dgw77dx8jb00380000gn/T/Naturals.tla
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module wire
Starting... (2026-06-22 10:22:07)
Computing initial states...
Computed 2 initial states...
Computed 4 initial states...
Finished computing initial states: 6 distinct states generated at 2026-06-22 10:22:08.
Error: Invariant NoOverdrafts is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
/\ people = {"alice", "bob"}
/\ sender = "alice"
/\ receiver = "bob"
/\ acc = [alice |-> 5, bob |-> 5]
/\ amount = 6
/\ pc = "Withdraw"

State 2: <Withdraw line 38, col 13 to line 41, col 63 of module wire>
/\ people = {"alice", "bob"}
/\ sender = "alice"
/\ receiver = "bob"
/\ acc = [alice |-> -1, bob |-> 5]
/\ amount = 6
/\ pc = "Deposit"

22 states generated, 17 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 3.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 1 and the 95th percentile is 1).
Finished in 00s at (2026-06-22 10:22:08)

#+end_example

* Rendering

There seems to be some built-in DOT rendering somewhere upstream that
should act as the starting point. This is likely another reason to
pull in the CLI code for local extension.
